
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
