
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: your_dockerhub_username/python-bankapp:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: "bankaccount_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort
  selector:
    app: bankapp
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
